# Generated by Django 5.0.9 on 2024-11-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0006_client_user_supplier_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='procedure',
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='prodHCM.supplier'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='procedure',
            field=models.ManyToManyField(blank=True, to='prodHCM.procedure'),
        ),
    ]
