# Generated by Django 5.0.9 on 2024-11-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0008_remove_insuranceplan_procedure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='insurancecompany',
            name='insurancePlan',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='insurance_type',
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='insuranceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodHCM.insurancecompany'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='procedure',
            field=models.ManyToManyField(blank=True, to='prodHCM.procedure'),
        ),
    ]
