# Generated by Django 5.0.9 on 2024-11-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0009_alter_insuranceplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='insuranceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodHCM.insurancecompany'),
        ),
    ]
