# Generated by Django 5.0.9 on 2024-11-13 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0010_alter_client_insurancecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='insuranceCompany',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurancePlan', to='prodHCM.insurancecompany'),
        ),
    ]
