# Generated by Django 5.0.9 on 2024-11-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0015_insurancecompanyprocedure_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='session_id'),
        ),
        migrations.AlterUniqueTogether(
            name='insurancecompanyprocedure',
            unique_together={('insuranceCompany', 'supplier', 'procedure')},
        ),
    ]
