# Generated by Django 5.0.9 on 2024-11-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0017_alter_beneficiaries_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='insurancePlan',
            field=models.ManyToManyField(blank=True, null=True, related_name='insurancePlan', to='prodHCM.insuranceplan'),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='procedure',
            field=models.ManyToManyField(blank=True, related_name='insurancePlan', to='prodHCM.procedure'),
        ),
    ]
