# Generated by Django 5.0.9 on 2024-11-16 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0018_client_insuranceplan_alter_insuranceplan_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiarieTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarieTreatment', to='prodHCM.beneficiaries')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarieTreatment', to='prodHCM.procedure')),
            ],
        ),
    ]
