# Generated by Django 5.0.9 on 2024-11-19 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0019_beneficiarietreatment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='category',
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='prodHCM.client'),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='insuranceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='prodHCM.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='insurancePlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='prodHCM.insuranceplan'),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da Completo'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='subCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure', to='prodHCM.subcategory'),
        ),
    ]
