# Generated by Django 5.0.9 on 2024-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0020_remove_procedure_category_alter_beneficiaries_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='procedure',
            field=models.ManyToManyField(blank=True, null=True, related_name='supplier', to='prodHCM.procedure'),
        ),
    ]
