# Generated by Django 5.0.9 on 2024-11-23 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0022_remove_supplier_procedure_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insurancecompanyprocedure',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='insurancePlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='prodHCM.insuranceplan'),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Completo'),
        ),
        migrations.AlterField(
            model_name='insurancecompanyprocedure',
            name='insuranceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceCompanyProcedure', to='prodHCM.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='insurancecompanyprocedure',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceCompanyProcedure', to='prodHCM.supplier'),
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Completo')),
                ('nuitNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='NUIT')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de celular')),
                ('date_of_activity_start', models.DateField(blank=True, null=True, verbose_name='Início de actividade')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='session_id')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='prodHCM.client')),
                ('insuranceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='prodHCM.insurancecompany')),
                ('insurancePlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='prodHCM.insuranceplan')),
            ],
        ),
    ]
