# Generated by Django 5.0.9 on 2024-11-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0023_alter_insurancecompanyprocedure_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuals',
            name='client',
        ),
        migrations.AddField(
            model_name='procedure',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
