# Generated by Django 5.0.9 on 2024-11-28 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0024_remove_individuals_client_procedure_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.RemoveField(
            model_name='beneficiarietreatment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='beneficiarietreatment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='date_of_activity_start',
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome do Plano'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='supplierType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subCategory', to='prodHCM.suppliertype'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplierType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure', to='prodHCM.suppliertype'),
        ),
    ]
