# Generated by Django 5.0.9 on 2024-11-28 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0025_suppliertype_remove_beneficiarietreatment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='supplierType',
        ),
        migrations.AddField(
            model_name='category',
            name='supplierType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subCategory', to='prodHCM.suppliertype'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplierType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='prodHCM.suppliertype'),
        ),
    ]
