# Generated by Django 5.0.9 on 2024-11-28 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0026_remove_subcategory_suppliertype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='firstUserName',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome do utilizador (Primeiro utilizador)'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='firstUserName',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome do utilizador (Primeiro utilizador)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='firstUserName',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome do utilizador (Primeiro utilizador)'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='insurancecompany',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='insuranceCompany', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ManyToManyField(related_name='supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
