# Generated by Django 5.0.9 on 2024-11-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0027_client_firstusername_insurancecompany_firstusername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='insuranceCompanyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insuranceCompany', to='prodHCM.insurancecompanytype'),
        ),
    ]
