# Generated by Django 5.0.9 on 2024-11-29 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0028_supplier_latitude_supplier_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='plafon',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Plafon'),
        ),
        migrations.AddField(
            model_name='individuals',
            name='percentageParticipation',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Percentagem de participação'),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('suspenso', 'Suspenso'), ('expirado', 'Expirado')], default='ativo', max_length=20, verbose_name='Status do Plano'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_color', models.CharField(blank=True, default='#000', max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/img/profile_logo/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img/profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
