# Generated by Django 5.0.9 on 2024-11-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0029_beneficiaries_plafon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='perParticipationBeneficiaries',
            field=models.CharField(max_length=255, null=True, verbose_name='Percentagem de participação Beneficiários'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='perParticipationCompay',
            field=models.CharField(max_length=255, null=True, verbose_name='Percentagem de participação da Empresa'),
        ),
    ]
