# Generated by Django 5.0.9 on 2024-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0030_insurancecompany_perparticipationbeneficiaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplan',
            name='plafon',
            field=models.CharField(blank=True, null=True, verbose_name='Plafon'),
        ),
    ]
