# Generated by Django 5.0.9 on 2025-01-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0034_remove_insurancecompanyprocedure_insurancecompany_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceplan',
            name='insuranceCompany',
        ),
        migrations.RemoveField(
            model_name='level',
            name='insuranceCompanyProcedure',
        ),
        migrations.AddField(
            model_name='insurancecompanyprocedure',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prodHCM.level'),
        ),
    ]
