# Generated by Django 5.0.9 on 2025-01-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0035_remove_insuranceplan_insurancecompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplan',
            name='insuranceCompany',
            field=models.ManyToManyField(blank=True, null=True, related_name='insuranceCompany', to='prodHCM.insurancecompany'),
        ),
    ]
