# Generated by Django 5.0.9 on 2025-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0037_alter_insuranceplan_insurancecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplan',
            name='teste',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
