# Generated by Django 5.0.9 on 2025-01-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0038_insuranceplan_teste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuranceplan',
            old_name='insuranceCompany',
            new_name='insuranceCompanys',
        ),
    ]
