# Generated by Django 5.0.9 on 2025-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0039_rename_insurancecompany_insuranceplan_insurancecompanys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceplan',
            name='insuranceCompanys',
        ),
        migrations.RemoveField(
            model_name='insuranceplan',
            name='teste',
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='insuranceCompany',
            field=models.ManyToManyField(blank=True, default=1, related_name='insuranceCompany', to='prodHCM.insurancecompany'),
        ),
    ]
