# Generated by Django 5.0.9 on 2025-01-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0040_remove_insuranceplan_insurancecompanys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='insuranceCompany',
            field=models.ManyToManyField(blank=True, default=1, null=True, related_name='insuranceCompany', to='prodHCM.insurancecompany'),
        ),
    ]
