# Generated by Django 5.0.9 on 2025-01-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0045_insuranceplan_hasplafonewqeq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='insuranceCompany',
            field=models.ManyToManyField(related_name='insurancePlan', to='prodHCM.insurancecompany'),
        ),
    ]
