# Generated by Django 5.0.9 on 2025-01-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0047_remove_insuranceplan_insurancecompany_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceplan',
            name='hasPlafonewqeq',
        ),
        migrations.AlterField(
            model_name='insurancecompanyprocedure',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceCompanyProcedure', to='prodHCM.procedure'),
        ),
    ]
