# Generated by Django 5.0.9 on 2025-01-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0049_client_insuranceplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompanyprocedure',
            name='insurancePlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceCompanyProcedure', to='prodHCM.insuranceplan'),
        ),
    ]
