# Generated by Django 5.0.9 on 2025-01-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0050_insurancecompanyprocedure_insuranceplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plafon', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Plafon')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaryLevel', to='prodHCM.level')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryICProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plafon', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plafon')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaryICProcedure', to='prodHCM.procedure')),
                ('beneficiary_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaryICProcedure', to='prodHCM.beneficiarylevel')),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plafon', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Plafon Restante')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('suspenso', 'Suspenso'), ('expirado', 'Expirado')], default='activo', max_length=20, verbose_name='Status do Plano')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_plans', to='prodHCM.beneficiaries')),
                ('insurancePlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_plans', to='prodHCM.insuranceplan')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiarylevel',
            name='beneficiary_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaryLevel', to='prodHCM.beneficiaryplan'),
        ),
    ]
