# Generated by Django 5.0.9 on 2025-01-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0052_rename_beneficiary_level_beneficiaryicprocedure_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarietreatment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
