# Generated by Django 5.0.9 on 2025-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0053_beneficiarietreatment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiarietreatment',
            name='procedure',
        ),
        migrations.AddField(
            model_name='beneficiarietreatment',
            name='procedure',
            field=models.ManyToManyField(blank=True, null=True, related_name='beneficiarieTreatment', to='prodHCM.procedure'),
        ),
    ]
