# Generated by Django 5.0.9 on 2025-01-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodHCM', '0054_remove_beneficiarietreatment_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiarietreatment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarieTreatment', to='prodHCM.supplier'),
        ),
    ]
